/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2014-02-27 02:50:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/view/common/common.jsp", Long.valueOf(1393400871969L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftiles_005finsert_0026_005ftemplate_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ftiles_005finsert_0026_005ftemplate_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ftiles_005finsert_0026_005ftemplate_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html lang=\"ja-JP\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>作業ガイドライン インデックス</title>\r\n");
      out.write("<meta name=\"description\" content=\"description\">\r\n");
      out.write("<meta name=\"keywords\" content=\"keywords\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=1024\">\r\n");
      out.write("<!-- commonImport ================== -->\r\n");
      out.write("<!-- CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/gcms_common/shared/css/common_import.css\">\r\n");
      out.write("<!-- JS -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"/gcms_common/shared/js/common_import.js\"></script>\r\n");
      out.write("<!-- /commonImport ================== -->\r\n");
      out.write("<!-- EachPage ================== -->\r\n");
      out.write("<!-- CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/gcms_common/_Oni/shared/css/dummy.css\">\r\n");
      out.write("<!-- JS -->\r\n");
      out.write("<!-- /EachPage ================== -->\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"Index\" class=\"pageType01\"><div id=\"Container\">\r\n");
      out.write("\r\n");
      out.write("<!-- NoScriptArea ================== -->\r\n");
      out.write("<noscript>\r\n");
      out.write("<p id=\"NoScriptArea\">当ウェブサイトを快適にご覧いただくには、ブラウザのJavaScript設定を有効にしていただく必要がございます。</p><!-- /NoScriptArea -->\r\n");
      out.write("</noscript>\r\n");
      out.write("<!-- /NoScriptArea ================== -->\r\n");
      out.write("\r\n");
      out.write("<!-- HeaderArea ================== -->\r\n");
      if (_jspx_meth_tiles_005finsert_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!--#include virtual=\"/gcms_common/shared/include/header.txt\" -->\r\n");
      out.write("<!-- /HeaderArea ================== -->\r\n");
      out.write("\r\n");
      out.write("<!-- ContentWrap ================== -->\r\n");
      out.write("<div id=\"ContentWrap\">\r\n");
      out.write("<div class=\"cwInnr01 clearfix\">\r\n");
      out.write("\r\n");
      out.write("<ul id=\"BreadcrumbList\">\r\n");
      out.write("<li><a href=\"/\">トップページ</a><span>></span></li><!--\r\n");
      out.write("--><li>作業ガイドライン インデックス</li><!--\r\n");
      out.write("--></ul>\r\n");
      out.write("\r\n");
      out.write("<!-- ContentMainArea ================== -->\r\n");
      out.write("<div id=\"ContentMainArea\">\r\n");
      out.write("\r\n");
      out.write("<h1 class=\"h1Basic01 sectS\"><span class=\"h1Inr01\">作業ガイドライン インデックス</span></h1>\r\n");
      out.write("\r\n");
      out.write("<div class=\"sectM\">\r\n");
      out.write("<h2 class=\"h2Basic01 sectS\">参照すべき資料</h2>\r\n");
      out.write("<ul class=\"list01 sectS\">\r\n");
      out.write("<li><a href=\"/_Oni/guide/guide_01.html\">仕様定義書</a></li>\r\n");
      out.write("<li>コーディング規則</li>\r\n");
      out.write("</ul><!-- /.list01 -->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- /.sectM -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"sectM\">\r\n");
      out.write("<h2 class=\"h2Basic01 sectS\">ファイルリスト</h2>\r\n");
      out.write("<ul class=\"list01 sectS\">\r\n");
      out.write("<li><a href=\"/_Oni/list/\">業務システム</a></li>\r\n");
      out.write("<li>マイページ（ユーザ使用システム）</li>\r\n");
      out.write("<li>エントランス(受付用)</li>\r\n");
      out.write("</ul><!-- /.list01 -->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- /.sectM -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"sectM\">\r\n");
      out.write("<h2 class=\"h2Basic01 sectS\">テンプレート</h2>\r\n");
      out.write("<ul class=\"list01 sectS\">\r\n");
      out.write("<li><a href=\"frame/frame_normal.html\">ページフレーム（がわ）</a></li>\r\n");
      out.write("<li><a href=\"frame/frame_one.html\">ページフレーム（がわ）：1カラムレイアウト</a></li>\r\n");
      out.write("</ul><!-- /.list01 -->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- /.sectM -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"sectM\">\r\n");
      out.write("<h2 class=\"h2Basic01 sectS\">モジュール</h2>\r\n");
      out.write("<p class=\"txtSub01 sectS\">※影響範囲を狭めるため<span class=\"txtAccent01\">#ContentMainArea</span>内で使用して下さい。</p>\r\n");
      out.write("<ul class=\"list01\">\r\n");
      out.write("<li><a href=\"/_Oni/module/module_01.html\">基本段落／区切り線</a></li>\r\n");
      out.write("<li><a href=\"/_Oni/module/module_02.html\">見出し／テキスト／リンク</a></li>\r\n");
      out.write("<li><a href=\"/_Oni/module/module_03.html\">リスト／表組み</a></li>\r\n");
      out.write("<li><a href=\"/_Oni/module/module_04.html\">ブロック幅／カラム／画像まわり</a></li>\r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- /.sectM -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"sectM\">\r\n");
      out.write("<h2 class=\"h2Basic01 sectS\">Javascriptテスト</h2>\r\n");
      out.write("<ul class=\"list01 sectS\">\r\n");
      out.write("<li><a href=\"test/calender.html\">カレンダー</a></li>\r\n");
      out.write("</ul><!-- /.list01 -->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- /.sectM -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"sectM\">\r\n");
      out.write("<h2 class=\"h2Basic01 sectS\">製作者メモ</h2>\r\n");
      out.write("<p>なし</p>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- /.sectM -->\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<!-- //ContentMainArea ================== -->\r\n");
      out.write("\r\n");
      out.write("<!-- ContentSubArea ================== -->\r\n");
      out.write("<!--#include virtual=\"/gcms_common/shared/include/subarea.txt\" -->\r\n");
      out.write("<!-- //ContentSubArea ================== -->\r\n");
      out.write("\r\n");
      out.write("</div><!-- /.cwInnr01 -->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- /ContentWrap ================== -->\r\n");
      out.write("\r\n");
      out.write("<!-- FooterArea ================== -->\r\n");
      if (_jspx_meth_tiles_005finsert_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!--#include virtual=\"/gcms_common/shared/include/footer.txt\" -->\r\n");
      out.write("<!-- /FooterArea ================== -->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- /#Container -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_tiles_005finsert_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insert
    org.apache.struts.taglib.tiles.InsertTag _jspx_th_tiles_005finsert_005f0 = (org.apache.struts.taglib.tiles.InsertTag) _005fjspx_005ftagPool_005ftiles_005finsert_0026_005ftemplate_005fnobody.get(org.apache.struts.taglib.tiles.InsertTag.class);
    _jspx_th_tiles_005finsert_005f0.setPageContext(_jspx_page_context);
    _jspx_th_tiles_005finsert_005f0.setParent(null);
    // /WEB-INF/view/index.jsp(32,0) name = template type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005finsert_005f0.setTemplate("common/header.jsp");
    int _jspx_eval_tiles_005finsert_005f0 = _jspx_th_tiles_005finsert_005f0.doStartTag();
    if (_jspx_th_tiles_005finsert_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ftiles_005finsert_0026_005ftemplate_005fnobody.reuse(_jspx_th_tiles_005finsert_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005ftiles_005finsert_0026_005ftemplate_005fnobody.reuse(_jspx_th_tiles_005finsert_005f0);
    return false;
  }

  private boolean _jspx_meth_tiles_005finsert_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insert
    org.apache.struts.taglib.tiles.InsertTag _jspx_th_tiles_005finsert_005f1 = (org.apache.struts.taglib.tiles.InsertTag) _005fjspx_005ftagPool_005ftiles_005finsert_0026_005ftemplate_005fnobody.get(org.apache.struts.taglib.tiles.InsertTag.class);
    _jspx_th_tiles_005finsert_005f1.setPageContext(_jspx_page_context);
    _jspx_th_tiles_005finsert_005f1.setParent(null);
    // /WEB-INF/view/index.jsp(116,0) name = template type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005finsert_005f1.setTemplate("common/footer.jsp");
    int _jspx_eval_tiles_005finsert_005f1 = _jspx_th_tiles_005finsert_005f1.doStartTag();
    if (_jspx_th_tiles_005finsert_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ftiles_005finsert_0026_005ftemplate_005fnobody.reuse(_jspx_th_tiles_005finsert_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005ftiles_005finsert_0026_005ftemplate_005fnobody.reuse(_jspx_th_tiles_005finsert_005f1);
    return false;
  }
}
