/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2014-02-27 02:49:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/view/common/common.jsp", Long.valueOf(1393400871969L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"HeaderArea\">\r\n");
      out.write("<div class=\"haInnr01 clearfix\">\r\n");
      out.write("<h1 id=\"Logo\">\r\n");
      out.write("<a href=\"/\">業務管理システム</a>\r\n");
      out.write("</h1>\r\n");
      out.write("<!-- /#Logo -->\r\n");
      out.write("<div id=\"LoginInfo\">\r\n");
      out.write("<p><span class=\"logId\">従業員ID:000000001</span><span class=\"logName\">氏名:鈴木一郎</span><a href=\"\" class=\"logLink\">ログアウト</a></p>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- /#LoginInfo -->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- /.haInnr01 -->\r\n");
      out.write("\r\n");
      out.write("<div id=\"GlobalNav\">\r\n");
      out.write("<ul><!--\r\n");
      out.write("--><li class=\"gnPnav current\"><a href=\"/menu.html\" accesskey=\"1\">マスタ登録</a>\r\n");
      out.write("<div class=\"subNavArea hide\">\r\n");
      out.write("<a href=\"/A10000101.html\">従業員区分登録</a>\r\n");
      out.write("<a href=\"/A10000102.html\">従業員区分一覧</a>\r\n");
      out.write("<a href=\"/list.html\">施設登録</a>\r\n");
      out.write("<a href=\"/knew.html\">施設一覧</a>\r\n");
      out.write("<a href=\"/klist.html\">ロッカー登録</a>\r\n");
      out.write("<a href=\"/klist.html\">ロッカー一覧</a>\r\n");
      out.write("<a href=\"/klist.html\">予約オプション登録</a>\r\n");
      out.write("<a href=\"/klist.html\">予約オプション一覧</a>\r\n");
      out.write("<a href=\"/klist.html\">プレイ時間登録</a>\r\n");
      out.write("<a href=\"/klist.html\">プレイ時間一覧</a>\r\n");
      out.write("</div>\r\n");
      out.write("</li><!--\r\n");
      out.write("--><li class=\"gnPnav\"><a href=\"order01_01.html\" accesskey=\"2\">従業員管理</a>\r\n");
      out.write("<div class=\"subNavArea hide\">\r\n");
      out.write("<a href=\"/A10000601.html\">従業員登録</a>\r\n");
      out.write("<a href=\"/A10000602.html\">従業員一覧</a>\r\n");
      out.write("</div>\r\n");
      out.write("</li><!--\r\n");
      out.write("--><li class=\"gnPnav\"><a href=\"order01_01.html\" accesskey=\"3\">予約管理</a>\r\n");
      out.write("<div class=\"subNavArea hide\">\r\n");
      out.write("<a href=\"/new.html\">予約登録</a>\r\n");
      out.write("<a href=\"/new.html\">予約一覧</a>\r\n");
      out.write("</div>\r\n");
      out.write("</li><!--\r\n");
      out.write("--><li class=\"gnPnav\"><a href=\"rder01_02.html\" accesskey=\"4\">当日処理</a>\r\n");
      out.write("<div class=\"subNavArea hide\">\r\n");
      out.write("<a href=\"/new.html\">スタート表</a>\r\n");
      out.write("<a href=\"/new.html\">チェックイン管理</a>\r\n");
      out.write("</div>\r\n");
      out.write("</li><!--\r\n");
      out.write("--><li class=\"gnPnav\"><a href=\"/order02_01.html\" accesskey=\"5\">会員管理</a>\r\n");
      out.write("<div class=\"subNavArea hide\">\r\n");
      out.write("<a href=\"/new.html\">会員登録</a>\r\n");
      out.write("<a href=\"/new.html\">会員一覧</a>\r\n");
      out.write("</div>\r\n");
      out.write("</li><!--\r\n");
      out.write("--><li class=\"gnPnav\"><a href=\"/order02_02.html\" accesskey=\"6\">経営管理</a>\r\n");
      out.write("<div class=\"subNavArea hide\">\r\n");
      out.write("<a href=\"/new.html\">会計管理</a>\r\n");
      out.write("<a href=\"/new.html\">各種売上データ</a>\r\n");
      out.write("</div>\r\n");
      out.write("</li><!--\r\n");
      out.write("--><li class=\"gnPnav\"><a href=\"/order02_02.html\" accesskey=\"7\">会計管理</a><!--\r\n");
      out.write("--></li><!--\r\n");
      out.write("--><li class=\"gnPnav\"><a href=\"/order02_02.html\" accesskey=\"8\">各種売上データ</a><!--\r\n");
      out.write("--></li></ul>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- /GlobalNav -->\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
