package org.apache.jsp.WEB_002dINF.view.management;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class account_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(1);
    _jspx_dependants.add("/WEB-INF/view/common/common.jsp");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftiles_005finsert_0026_005ftemplate_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ftiles_005finsert_0026_005ftemplate_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ftiles_005finsert_0026_005ftemplate_005fnobody.release();
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html lang=\"ja-JP\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>会計管理 | 経営管理 | 作業ガイドライン インデックス</title>\r\n");
      out.write("<meta name=\"description\" content=\"description\">\r\n");
      out.write("<meta name=\"keywords\" content=\"keywords\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=1024\">\r\n");
      out.write("<!-- commonImport ================== -->\r\n");
      out.write("<!-- CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/gcms_common/shared/css/common_import.css\">\r\n");
      out.write("<!-- JS -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"/gcms_common/shared/js/common_import.js\"></script>\r\n");
      out.write("<!-- /commonImport ================== -->\r\n");
      out.write("<!-- EachPage ================== -->\r\n");
      out.write("<!-- CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/gcms_common/shared/css/pages.css\">\r\n");
      out.write("<link type=\"text/css\" href=\"http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/ui-lightness/jquery-ui.css\" rel=\"stylesheet\" />\r\n");
      out.write("<!-- JS -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://ajax.googleapis.com/ajax/libs/jqueryui/1/jquery-ui.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://ajax.googleapis.com/ajax/libs/jqueryui/1/i18n/jquery.ui.datepicker-ja.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t$(\".tabList li\").bind(\"click\",function(){\r\n");
      out.write("\t\t\tvar num = $(\".tabList li\").index(this);\r\n");
      out.write("\t\t\t$(\".tabList li.current\").removeClass(\"current\")\r\n");
      out.write("\t\t\t$(this).addClass(\"current\");\r\n");
      out.write("\t\t\t$(\"#TabArea01 .tabBody.current\").removeClass(\"current\")\r\n");
      out.write("\t\t\t$(\"#TabArea01 .tabBody\").eq(num).addClass(\"current\");\r\n");
      out.write("\t\t\t// alert(\"test\")\r\n");
      out.write("\t\t});\r\n");
      out.write("\t})\r\n");
      out.write("\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t　$(\"#datepicker\").datepicker({\r\n");
      out.write("\t　　numberOfMonths: 1,\r\n");
      out.write("\t　　showButtonPanel: true\r\n");
      out.write("\t　});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"//www.google.com/jsapi\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("      google.load('visualization', '1', {packages: ['corechart']});\r\n");
      out.write("    </script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("      function drawVisualization() {\r\n");
      out.write("        // Create and populate the data table.\r\n");
      out.write("        var data = google.visualization.arrayToDataTable([\r\n");
      out.write("            [\"時間\",\"プレイ人数\"],\r\n");
      out.write("  [\"6:00\",2],\r\n");
      out.write("  [\"7:00\",1],\r\n");
      out.write("  [\"8:00\",1],\r\n");
      out.write("  [\"9:00\",2],\r\n");
      out.write("  [\"10:00\",4],\r\n");
      out.write("  [\"11:00\",5],\r\n");
      out.write("  [\"12:00\",3],\r\n");
      out.write("  [\"13:00\",1],\r\n");
      out.write("  [\"14:00\",1],\r\n");
      out.write("  [\"15:00\",2],\r\n");
      out.write("  [\"16:00\",4],\r\n");
      out.write("  [\"17:00\",5],\r\n");
      out.write("  [\"18:00\",3],\r\n");
      out.write("        ]);\r\n");
      out.write("\r\n");
      out.write("        // Create and draw the visualization.\r\n");
      out.write("        new google.visualization.ColumnChart(document.getElementById('visualization')).\r\n");
      out.write("            draw(data,\r\n");
      out.write("                 {\r\n");
      out.write("                  width:1000, height:250,\r\n");
      out.write("                  hAxis: {title: \"\"}}\r\n");
      out.write("            );\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      google.setOnLoadCallback(drawVisualization);\r\n");
      out.write("    </script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write(" // Visualization API と折れ線グラフ用のパッケージのロード\r\n");
      out.write(" google.load(\"visualization\", \"1\", {packages:[\"corechart\"]});\r\n");
      out.write("\r\n");
      out.write(" // Google Visualization API ロード時のコールバック関数の設定\r\n");
      out.write(" google.setOnLoadCallback(drawChart);\r\n");
      out.write("\r\n");
      out.write(" // グラフ作成用のコールバック関数\r\n");
      out.write(" function drawChart() {\r\n");
      out.write(" \t//データテーブルの作成\r\n");
      out.write("\tvar data = google.visualization.arrayToDataTable(\r\n");
      out.write("\t\t[ ['時間', '売上'],[\"6:00\",2],\r\n");
      out.write("  [\"7:00\",14000],\r\n");
      out.write("  [\"8:00\",24355],\r\n");
      out.write("  [\"9:00\",20044],\r\n");
      out.write("  [\"9:00\",20000],\r\n");
      out.write("  [\"10:00\",43200],\r\n");
      out.write("  [\"11:00\",42500],\r\n");
      out.write("  [\"12:00\",50900],\r\n");
      out.write("  [\"13:00\",45600],\r\n");
      out.write("  [\"14:00\",34500],\r\n");
      out.write("  [\"15:00\",23400],\r\n");
      out.write("  [\"16:00\",42200],\r\n");
      out.write("  [\"17:00\",45500],\r\n");
      out.write("  [\"18:00\",50900]\r\n");
      out.write("\t]);\r\n");
      out.write("\r\n");
      out.write("\t // グラフのオプションを設定\r\n");
      out.write("\tvar options = { title: '' , height: 250};\r\n");
      out.write("\r\n");
      out.write("\t// LineChart のオブジェクトの作成\r\n");
      out.write("\tvar chart = new google.visualization.LineChart(document.getElementById('visualization02'));\r\n");
      out.write("\r\n");
      out.write("\t// データテーブルとオプションを渡して、グラフを描画\r\n");
      out.write(" \tchart.draw(data, options);\r\n");
      out.write(" }\r\n");
      out.write("    </script>\r\n");
      out.write("<!-- /EachPage ================== -->\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"A006020\" class=\"pageType01 oneColumn\"><div id=\"Container\">\r\n");
      out.write("\r\n");
      out.write("<!-- NoScriptArea ================== -->\r\n");
      out.write("<noscript>\r\n");
      out.write("<p id=\"NoScriptArea\">当ウェブサイトを快適にご覧いただくには、ブラウザのJavaScript設定を有効にしていただく必要がございます。</p><!-- /NoScriptArea -->\r\n");
      out.write("</noscript>\r\n");
      out.write("<!-- /NoScriptArea ================== -->\r\n");
      out.write("\r\n");
      out.write("<!-- HeaderArea ================== -->\r\n");
      if (_jspx_meth_tiles_005finsert_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!-- /HeaderArea ================== -->\r\n");
      out.write("\r\n");
      out.write("<!-- ContentWrap ================== -->\r\n");
      out.write("<div id=\"ContentWrap\">\r\n");
      out.write("<div class=\"cwInnr01 clearfix\">\r\n");
      out.write("\r\n");
      out.write("<ul id=\"BreadcrumbList\">\r\n");
      out.write("<li><a href=\"/\">トップページ</a><span>></span></li><!--\r\n");
      out.write("--><li>経営管理<span>></span></li><!--\r\n");
      out.write("--><li>会計管理</li><!--\r\n");
      out.write("--></ul>\r\n");
      out.write("<!-- #BreadcrumbList -->\r\n");
      out.write("\r\n");
      out.write("<!-- ContentMainArea ================== -->\r\n");
      out.write("<div id=\"ContentMainArea\">\r\n");
      out.write("\r\n");
      out.write("\t<h1 class=\"h1Basic01 sectS\"><span class=\"h1Inr01\">会計管理</span></h1>\r\n");
      out.write("\r\n");
      out.write("\t<p class=\"txtRight txtSpe01\">現在会員数　<em>○○○○○○人</em></p>\r\n");
      out.write("\r\n");
      out.write("\t<ul class=\"tabList sectS\">\r\n");
      out.write("\t\t<li class=\"current\">日報会計管理</li>\r\n");
      out.write("\t\t<li>週間会計管理</li>\r\n");
      out.write("\t\t<li>月間会計管理</li>\r\n");
      out.write("\t\t<li>四半期会計管理</li>\r\n");
      out.write("\t\t<li>年間会計管理</li>\r\n");
      out.write("\t\t<li>累計会計管理</li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"TabArea01\" class=\"current\">\r\n");
      out.write("\t\t<div class=\"tabBody current\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<p class=\"sectS\">\r\n");
      out.write("\t\t\t\t日付　<input type=\"text\" class=\"inpTxt01\" id=\"datepicker\"> <input type=\"button\" value=\"出力\" class=\"inpBtn03\">\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"clearfix sectS\">\r\n");
      out.write("\t\t\t\t<p class=\"posRight\">\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"PDF出力\" class=\"inpBtn03\">\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"CSV出力\" class=\"inpBtn03\">\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<table class=\"tbl01 sectM\">\r\n");
      out.write("\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t<col style=\"width:25%\">\r\n");
      out.write("\t\t\t\t\t<col style=\"width:25%\">\r\n");
      out.write("\t\t\t\t\t<col style=\"width:25%\">\r\n");
      out.write("\t\t\t\t\t<col style=\"width:25%\">\r\n");
      out.write("\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t<!-- row -->\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>プレイ人数合計</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\">○○人</span></td>\r\n");
      out.write("\t\t\t\t\t\t<th>ビジター会員利用者数</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\">○○人</span></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<!-- /row -->\r\n");
      out.write("\t\t\t\t\t<!-- row -->\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>プレイ組数合計</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\">○○組</span></td>\r\n");
      out.write("\t\t\t\t\t\t<th>会員数増減</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\" class=\"txtAccent02\">+1人</span></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<!-- /row -->\r\n");
      out.write("\t\t\t\t\t<!-- row -->\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>プレイ料金売上合計</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\">\\210000</span></td>\r\n");
      out.write("\t\t\t\t\t\t<th rowspan=\"2\" class=\"vTxtMiddle\">合計売上</th>\r\n");
      out.write("\t\t\t\t\t\t<td rowspan=\"2\" class=\"vTxtMiddle\"><span id=\"\">\\260000</span></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<!-- /row -->\r\n");
      out.write("\t\t\t\t\t<!-- row -->\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>施設売上合計</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\">\\50000</span></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<!-- /row -->\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div><!-- /.tabBody -->\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"tabBody\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"clearfix sectS\">\r\n");
      out.write("\t\t\t\t<p class=\"posRight\">\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"PDF出力\" class=\"inpBtn03\">\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"CSV出力\" class=\"inpBtn03\">\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<table class=\"tbl01 sectM\">\r\n");
      out.write("\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t<col style=\"width:25%\">\r\n");
      out.write("\t\t\t\t\t<col style=\"width:25%\">\r\n");
      out.write("\t\t\t\t\t<col style=\"width:25%\">\r\n");
      out.write("\t\t\t\t\t<col style=\"width:25%\">\r\n");
      out.write("\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t<!-- row -->\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>プレイ人数合計</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\">○○人</span></td>\r\n");
      out.write("\t\t\t\t\t\t<th>施設売上合計</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\">50000</span></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<!-- /row -->\r\n");
      out.write("\t\t\t\t\t<!-- row -->\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>プレー人数合計前週比</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\" class=\"txtAccent01\">-42人</span></td>\r\n");
      out.write("\t\t\t\t\t\t<th>施設売上前週比</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\" class=\"txtAccent02\">+5%</span></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<!-- /row -->\r\n");
      out.write("\t\t\t\t\t<!-- row -->\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>プレー組数合計</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\">７組</span></td>\r\n");
      out.write("\t\t\t\t\t\t<th>ビジター会員利用者数</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\">18人</span></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<!-- /row -->\r\n");
      out.write("\t\t\t\t\t<!-- row -->\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>プレー組数合計前週比</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\" class=\"txtAccent01\">-4組</span></td>\r\n");
      out.write("\t\t\t\t\t\t<th>会員数増減</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\" class=\"txtAccent02\">＋1人</span></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<!-- /row -->\r\n");
      out.write("\t\t\t\t\t<!-- row -->\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>プレー料金売上合計</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\">210000</span></td>\r\n");
      out.write("\t\t\t\t\t\t<th>合計売上</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\">260000</span></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<!-- /row -->\r\n");
      out.write("\t\t\t\t\t<!-- row -->\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>プレー料金売上前週比</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\">-20%</span></td>\r\n");
      out.write("\t\t\t\t\t\t<th>合計売上前週比</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\" class=\"txtAccent01\">-1%</span></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<!-- /row -->\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div><!-- /.tabBody -->\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"tabBody\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"clearfix sectS\">\r\n");
      out.write("\t\t\t\t<p class=\"posRight\">\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"PDF出力\" class=\"inpBtn03\">\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"CSV出力\" class=\"inpBtn03\">\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<table class=\"tbl01 sectM\">\r\n");
      out.write("\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t<col style=\"width:25%\">\r\n");
      out.write("\t\t\t\t\t<col style=\"width:25%\">\r\n");
      out.write("\t\t\t\t\t<col style=\"width:25%\">\r\n");
      out.write("\t\t\t\t\t<col style=\"width:25%\">\r\n");
      out.write("\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t<!-- row -->\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>プレイ人数合計</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\">○○人</span></td>\r\n");
      out.write("\t\t\t\t\t\t<th>施設売上合計</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\">50000</span></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<!-- /row -->\r\n");
      out.write("\t\t\t\t\t<!-- row -->\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>プレー人数合計前週比</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\" class=\"txtAccent01\">-42人</span></td>\r\n");
      out.write("\t\t\t\t\t\t<th>施設売上前週比</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\" class=\"txtAccent02\">+5%</span></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<!-- /row -->\r\n");
      out.write("\t\t\t\t\t<!-- row -->\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>プレー組数合計</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\">７組</span></td>\r\n");
      out.write("\t\t\t\t\t\t<th>ビジター会員利用者数</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\">18人</span></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<!-- /row -->\r\n");
      out.write("\t\t\t\t\t<!-- row -->\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>プレー組数合計前週比</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\" class=\"txtAccent01\">-4組</span></td>\r\n");
      out.write("\t\t\t\t\t\t<th>会員数増減</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\" class=\"txtAccent02\">＋1人</span></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<!-- /row -->\r\n");
      out.write("\t\t\t\t\t<!-- row -->\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>プレー料金売上合計</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\">210000</span></td>\r\n");
      out.write("\t\t\t\t\t\t<th>合計売上</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\">260000</span></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<!-- /row -->\r\n");
      out.write("\t\t\t\t\t<!-- row -->\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>プレー料金売上前週比</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\">-20%</span></td>\r\n");
      out.write("\t\t\t\t\t\t<th>合計売上前週比</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\" class=\"txtAccent01\">-1%</span></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<!-- /row -->\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div><!-- /.tabBody -->\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"tabBody\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"clearfix sectS\">\r\n");
      out.write("\t\t\t\t<p class=\"posRight\">\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"PDF出力\" class=\"inpBtn03\">\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"CSV出力\" class=\"inpBtn03\">\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<table class=\"tbl01 sectM\">\r\n");
      out.write("\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t<col style=\"width:25%\">\r\n");
      out.write("\t\t\t\t\t<col style=\"width:25%\">\r\n");
      out.write("\t\t\t\t\t<col style=\"width:25%\">\r\n");
      out.write("\t\t\t\t\t<col style=\"width:25%\">\r\n");
      out.write("\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t<!-- row -->\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>プレイ人数合計</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\">○○人</span></td>\r\n");
      out.write("\t\t\t\t\t\t<th>施設売上合計</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\">50000</span></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<!-- /row -->\r\n");
      out.write("\t\t\t\t\t<!-- row -->\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>プレー人数合計前週比</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\" class=\"txtAccent01\">-42人</span></td>\r\n");
      out.write("\t\t\t\t\t\t<th>施設売上前週比</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\" class=\"txtAccent02\">+5%</span></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<!-- /row -->\r\n");
      out.write("\t\t\t\t\t<!-- row -->\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>プレー組数合計</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\">７組</span></td>\r\n");
      out.write("\t\t\t\t\t\t<th>ビジター会員利用者数</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\">18人</span></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<!-- /row -->\r\n");
      out.write("\t\t\t\t\t<!-- row -->\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>プレー組数合計前週比</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\" class=\"txtAccent01\">-4組</span></td>\r\n");
      out.write("\t\t\t\t\t\t<th>会員数増減</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\" class=\"txtAccent02\">＋1人</span></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<!-- /row -->\r\n");
      out.write("\t\t\t\t\t<!-- row -->\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>プレー料金売上合計</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\">210000</span></td>\r\n");
      out.write("\t\t\t\t\t\t<th>合計売上</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\">260000</span></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<!-- /row -->\r\n");
      out.write("\t\t\t\t\t<!-- row -->\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>プレー料金売上前週比</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\">-20%</span></td>\r\n");
      out.write("\t\t\t\t\t\t<th>合計売上前週比</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\" class=\"txtAccent01\">-1%</span></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<!-- /row -->\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div><!-- /.tabBody -->\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"tabBody\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"clearfix sectS\">\r\n");
      out.write("\t\t\t\t<p class=\"posRight\">\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"PDF出力\" class=\"inpBtn03\">\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"CSV出力\" class=\"inpBtn03\">\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<table class=\"tbl01 sectM\">\r\n");
      out.write("\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t<col style=\"width:25%\">\r\n");
      out.write("\t\t\t\t\t<col style=\"width:25%\">\r\n");
      out.write("\t\t\t\t\t<col style=\"width:25%\">\r\n");
      out.write("\t\t\t\t\t<col style=\"width:25%\">\r\n");
      out.write("\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t<!-- row -->\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>プレイ人数合計</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\">○○人</span></td>\r\n");
      out.write("\t\t\t\t\t\t<th>施設売上合計</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\">50000</span></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<!-- /row -->\r\n");
      out.write("\t\t\t\t\t<!-- row -->\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>プレー人数合計前週比</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\" class=\"txtAccent01\">-42人</span></td>\r\n");
      out.write("\t\t\t\t\t\t<th>施設売上前週比</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\" class=\"txtAccent02\">+5%</span></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<!-- /row -->\r\n");
      out.write("\t\t\t\t\t<!-- row -->\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>プレー組数合計</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\">７組</span></td>\r\n");
      out.write("\t\t\t\t\t\t<th>ビジター会員利用者数</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\">18人</span></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<!-- /row -->\r\n");
      out.write("\t\t\t\t\t<!-- row -->\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>プレー組数合計前週比</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\" class=\"txtAccent01\">-4組</span></td>\r\n");
      out.write("\t\t\t\t\t\t<th>会員数増減</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\" class=\"txtAccent02\">＋1人</span></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<!-- /row -->\r\n");
      out.write("\t\t\t\t\t<!-- row -->\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>プレー料金売上合計</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\">210000</span></td>\r\n");
      out.write("\t\t\t\t\t\t<th>合計売上</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\">260000</span></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<!-- /row -->\r\n");
      out.write("\t\t\t\t\t<!-- row -->\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>プレー料金売上前週比</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\">-20%</span></td>\r\n");
      out.write("\t\t\t\t\t\t<th>合計売上前週比</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\" class=\"txtAccent01\">-1%</span></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<!-- /row -->\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div><!-- /.tabBody -->\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"tabBody\">\r\n");
      out.write("\t\t\t<div class=\"clearfix sectS\">\r\n");
      out.write("\t\t\t\t<p class=\"posRight\">\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"PDF出力\" class=\"inpBtn03\">\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"CSV出力\" class=\"inpBtn03\">\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<table class=\"tbl01 sectM\">\r\n");
      out.write("\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t<col style=\"width:25%\">\r\n");
      out.write("\t\t\t\t\t<col style=\"width:25%\">\r\n");
      out.write("\t\t\t\t\t<col style=\"width:25%\">\r\n");
      out.write("\t\t\t\t\t<col style=\"width:25%\">\r\n");
      out.write("\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t<!-- row -->\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>プレイ人数合計</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\">○○人</span></td>\r\n");
      out.write("\t\t\t\t\t\t<th>施設売上合計</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\">50000</span></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<!-- /row -->\r\n");
      out.write("\t\t\t\t\t<!-- row -->\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>プレー人数合計前週比</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\" class=\"txtAccent01\">-42人</span></td>\r\n");
      out.write("\t\t\t\t\t\t<th>施設売上前週比</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\" class=\"txtAccent02\">+5%</span></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<!-- /row -->\r\n");
      out.write("\t\t\t\t\t<!-- row -->\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>プレー組数合計</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\">７組</span></td>\r\n");
      out.write("\t\t\t\t\t\t<th>ビジター会員利用者数</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\">18人</span></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<!-- /row -->\r\n");
      out.write("\t\t\t\t\t<!-- row -->\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>プレー組数合計前週比</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\" class=\"txtAccent01\">-4組</span></td>\r\n");
      out.write("\t\t\t\t\t\t<th>会員数増減</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\" class=\"txtAccent02\">＋1人</span></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<!-- /row -->\r\n");
      out.write("\t\t\t\t\t<!-- row -->\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>プレー料金売上合計</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\">210000</span></td>\r\n");
      out.write("\t\t\t\t\t\t<th>合計売上</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\">260000</span></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<!-- /row -->\r\n");
      out.write("\t\t\t\t\t<!-- row -->\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>プレー料金売上前週比</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\">-20%</span></td>\r\n");
      out.write("\t\t\t\t\t\t<th>合計売上前週比</th>\r\n");
      out.write("\t\t\t\t\t\t<td><span id=\"\" class=\"txtAccent01\">-1%</span></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<!-- /row -->\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div><!-- /.tabBody -->\r\n");
      out.write("\r\n");
      out.write("\t\t<h2 class=\"h2Basic01 sectS\">プレイ人数</h2>\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"visualization\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t<h2 class=\"h2Basic01 sectS\">売上</h2>\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"visualization02\"></div>\r\n");
      out.write("\r\n");
      out.write("\t</div><!-- /#TabArea01 -->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- //ContentMainArea ================== -->\r\n");
      out.write("\r\n");
      out.write("</div><!-- /.cwInnr01 -->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- /ContentWrap ================== -->\r\n");
      out.write("\r\n");
      out.write("<!-- FooterArea ================== -->\r\n");
      if (_jspx_meth_tiles_005finsert_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!-- /FooterArea ================== -->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- /#Container -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else log(t.getMessage(), t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_tiles_005finsert_005f0(PageContext _jspx_page_context)
          throws Throwable {
    PageContext pageContext = _jspx_page_context;
    JspWriter out = _jspx_page_context.getOut();
    //  tiles:insert
    org.apache.struts.taglib.tiles.InsertTag _jspx_th_tiles_005finsert_005f0 = (org.apache.struts.taglib.tiles.InsertTag) _005fjspx_005ftagPool_005ftiles_005finsert_0026_005ftemplate_005fnobody.get(org.apache.struts.taglib.tiles.InsertTag.class);
    _jspx_th_tiles_005finsert_005f0.setPageContext(_jspx_page_context);
    _jspx_th_tiles_005finsert_005f0.setParent(null);
    // /WEB-INF/view/management/account.jsp(127,0) name = template type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005finsert_005f0.setTemplate("../common/header.jsp");
    int _jspx_eval_tiles_005finsert_005f0 = _jspx_th_tiles_005finsert_005f0.doStartTag();
    if (_jspx_th_tiles_005finsert_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ftiles_005finsert_0026_005ftemplate_005fnobody.reuse(_jspx_th_tiles_005finsert_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005ftiles_005finsert_0026_005ftemplate_005fnobody.reuse(_jspx_th_tiles_005finsert_005f0);
    return false;
  }

  private boolean _jspx_meth_tiles_005finsert_005f1(PageContext _jspx_page_context)
          throws Throwable {
    PageContext pageContext = _jspx_page_context;
    JspWriter out = _jspx_page_context.getOut();
    //  tiles:insert
    org.apache.struts.taglib.tiles.InsertTag _jspx_th_tiles_005finsert_005f1 = (org.apache.struts.taglib.tiles.InsertTag) _005fjspx_005ftagPool_005ftiles_005finsert_0026_005ftemplate_005fnobody.get(org.apache.struts.taglib.tiles.InsertTag.class);
    _jspx_th_tiles_005finsert_005f1.setPageContext(_jspx_page_context);
    _jspx_th_tiles_005finsert_005f1.setParent(null);
    // /WEB-INF/view/management/account.jsp(575,0) name = template type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005finsert_005f1.setTemplate("../common/footer.jsp");
    int _jspx_eval_tiles_005finsert_005f1 = _jspx_th_tiles_005finsert_005f1.doStartTag();
    if (_jspx_th_tiles_005finsert_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ftiles_005finsert_0026_005ftemplate_005fnobody.reuse(_jspx_th_tiles_005finsert_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005ftiles_005finsert_0026_005ftemplate_005fnobody.reuse(_jspx_th_tiles_005finsert_005f1);
    return false;
  }
}
